title: Nectar Research Cloud tutorials
email: support@ehelp.edu.au
description: Nectar Research Cloud tutorials
baseurl:
permalink: none

markdown: kramdown

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

repository: NeCTAR-RC/tutorials

liquid:
  error_mode: strict

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: tutorial

# Ordered by how they should appear in the curriculum list
tutorial_categories:
  - Setting up prerequisites
  - Launching and connecting
  - The command line and software
  - Data
  - Networking
  - Working with allocations
  - Cloud-native services

# New tutorials should be added by running:
#   $ rake tutorial "My tutorial title"
collections:
  