name: Request Minor Changes
description: Suggest minor changes to an existing tutorial
labels: ["improvement"]

body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to suggest improvements to a tutorial."
  - type: markdown
    attributes:
      value: "Note: Please search to see if an issue already exists for your suggested improvement."

  - type: input
    id: changes-summary
    attributes:
      label: Changes Summary
      description: "Enter a brief summary of your suggested changes. Make sure to include the tutorial name and page/s to which your changes apply."
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: "How can we get in touch with you if we need more information?"
      placeholder: e.g. email@example.com
    validations:
      required: true