name: Request Tutorial
description: Suggest an idea for a tutorial that you would find helpful
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to suggest a new tutorial."
  - type: markdown
    attributes:
      value: "Note: Please search to see if an issue already exists for your suggested tutorial."

  - type: input
    id: tutorial-summary
    attributes:
      label: Tutorial Summary
      description: "Please enter a brief summary of the tutorial."
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: "How can we get in touch with you if we need more information?"
      placeholder: e.g. email@example.com
    validations:
      required: true