title: AAF Dev Portal
email: support@aaf.edu.au
description: Documentation for technical connection to the AAF
baseurl:
permalink: none

markdown: kramdown

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

repository: ausaccessfed/dev-portal

liquid:
  error_mode: strict

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: tutorial

# Ordered by how they should appear in the curriculum list
tutorial_categories:
  - AAF Connection Types
  - Integration
  - Federation Manager Authentication
  - Connect a Service
  - Identity Management Solutions

# New tutorials should be added by running:
#   $ rake tutorial "My tutorial title"
collections:
  connect-with-keycloak:
    output: true
    permalink: /:collection/:name
    title: Connect with Keycloak
    summary: A tutorial for connecting with Keycloak
    category: Identity Management Solutions
    curriculum: OpenID Connect
    level: Beginner
    tags:
      - keycloak
      - openid connect
      - tutorial
    difficulty: 1
    duration: 10
    status: draft
    published: 2024-02-06
    author: Your Name <your.name@email.domain>

  connection-types:
    output: true
    permalink: /:collection/:name
    title: Connection Types
    summary: An overview of connection types available
    category: AAF Connection Types
    level: Beginner
    tags:
      - connect
      - overview
    difficulty: 1
    duration: 10
    status: draft
    published: 2024-02-06
    author: Your Name <your.name@email.domain>

  log-into-federation-manager:
    output: true
    permalink: /:collection/:name
    title: Log into Federation Manager
    summary: A tutorial for logging into Federation Manager
    category: Federation Manager Authentication
    level: Beginner
    tags:
      - authentication
      - federation manager
      - tutorial
    difficulty: 1
    duration: 10
    status: draft
    published: 2024-02-06
    author: Your Name <your.name@email.domain>

  openid-connect-integration:
    output: true
    permalink: /:collection/:name
    title: OpenID Connect Integration
    summary: A tutorial for OpenID Connect integration
    category: Integration
    curriculum: OpenID Connect
    level: Beginner
    tags:
      - openid connect
      - tutorial
    difficulty: 1
    duration: 10
    status: draft
    published: 2024-02-06
    author: Your Name <your.name@email.domain>
  
  rapid-connect-integration:
    output: true
    permalink: /:collection/:name
    title: Rapid Connect Integration
    summary: A tutorial for Rapid Connect integration
    category: Integration
    curriculum: Rapid Connect
    level: Beginner
    tags:
      - rapid connect
      - tutorial
    difficulty: 1
    duration: 10
    status: draft
    published: 2024-02-06
    author: Your Name <your.name@email.domain>

  saml-integration:
    output: true
    permalink: /:collection/:name
    title: SAML Integration
    summary: A tutorial for SAML integration
    category: Integration
    curriculum: SAML
    level: Advanced
    tags:
      - saml
      - tutorial
    difficulty: 4
    duration: 60
    status: draft
    published: 2024-02-06
    author: Your Name <your.name@email.domain>

  connect-an-oidc-service:
    output: true
    permalink: /:collection/:name
    title: Connect an OIDC Service
    summary: A tutorial for connecting an OIDC Service
    category: Connect a Service
    curriculum: OpenID Connect
    level: Beginner
    tags:
      - openid connect
      - tutorial
    difficulty: 1
    duration: 10
    status: draft
    published: 2024-02-06
    author: Your Name <your.name@email.domain>

  connect-a-rapid-connect-service:
    output: true
    permalink: /:collection/:name
    title: Connect a Rapid Connect Service
    summary: A tutorial for connecting a Rapid Connect service
    category: Connect a Service
    curriculum: Rapid Connect
    level: Beginner
    tags:
      - rapid connect
      - tutorial
    difficulty: 1
    duration: 10
    status: draft
    published: 2024-02-06
    author: Your Name <your.name@email.domain>

  connect-a-saml-service:
    output: true
    permalink: /:collection/:name
    title: Connect a SAML Service
    summary: A tutorial for connecting a SAML service
    category: Connect a Service
    curriculum: SAML
    level: Advanced
    tags:
      - saml
      - tutorial
    difficulty: 4
    duration: 10
    status: draft
    published: 2024-02-06
    author: Your Name <your.name@email.domain>

  verifid-integration:
    output: true
    permalink: /:collection/:name
    title: VerifID Integration
    summary: A tutorial for VerifID integration
    category: Integration
    curriculum: VerifID
    level: Beginner # Beginner|Intermediate|Advanced|Series|Non-technical
    tags:
      - tutorial
      - verifid
    difficulty: 1 # number from 1 to 5
    duration: 10 # number of minutes
    status: draft # draft or published
    published: 2024-02-14
    author: Your Name <your.name@email.domain>

  connect-with-verifid:
    output: true
    permalink: /:collection/:name
    title: Connect with VerifID
    summary: A tutorial for connecting with VerifID
    category: Connect a Service
    curriculum: VerifID
    level: Beginner # Beginner|Intermediate|Advanced|Series|Non-technical
    tags:
      - tutorial
      - verifid
    difficulty: 1 # number from 1 to 5
    duration: 10 # number of minutes
    status: draft # draft or published
    published: 2024-02-16
    author: Your Name <your.name@email.domain>

  openid-connect-series:
    output: true
    permalink: /:collection/:name
    title: OpenID Connect Series
    summary: Integrate and connect with OIDC
    curriculum: OpenID Connect
    level: Series # Beginner|Intermediate|Advanced|Series|Non-technical
    tags:
      - series
      - beginner
    difficulty: 1 # number from 1 to 5
    duration: 10 # number of minutes
    status: draft # draft or published
    published: 2024-02-28
    author: Your Name <your.name@email.domain>

  rapid-connect-series:
    output: true
    permalink: /:collection/:name
    title: Rapid Connect Series
    summary: Integrate and connect with Rapid Connect
    curriculum: Rapid Connect
    level: Series # Beginner|Intermediate|Advanced|Series|Non-technical
    tags:
      - series
      - beginner
    difficulty: 1 # number from 1 to 5
    duration: 10 # number of minutes
    status: draft # draft or published
    published: 2024-02-29
    author: Your Name <your.name@email.domain>

  verifid-series:
    output: true
    permalink: /:collection/:name
    title: VerifID Series
    summary: Integrate and connect with VerifID
    curriculum: VerifID
    level: Series # Beginner|Intermediate|Advanced|Series|Non-technical
    tags:
      - series
      - beginner
    difficulty: 1 # number from 1 to 5
    duration: 10 # number of minutes
    status: draft # draft or published
    published: 2024-02-29
    author: Your Name <your.name@email.domain>

  saml-series:
    output: true
    permalink: /:collection/:name
    title: SAML Series
    summary: Integrate and connect with SAML
    curriculum: SAML
    level: Series # Beginner|Intermediate|Advanced|Series|Non-technical
    tags:
      - series
      - advanced
    difficulty: 4 # number from 1 to 5
    duration: 70 # number of minutes
    status: draft # draft or published
    published: 2024-02-29
    author: Your Name <your.name@email.domain>

  connect-to-edugain:
    output: true
    permalink: /:collection/:name
    title: Connect to eduGAIN
    summary: A tutorial for connecting to eduGAIN
    level: Beginner # Beginner|Intermediate|Advanced|Series|Non-technical
    tags:
      - tutorial
      - eduGAIN
    difficulty: 1 # number from 1 to 5
    duration: 10 # number of minutes
    status: draft # draft or published
    published: 2024-03-05
    author: Your Name <your.name@email.domain>

