title: AAF Dev Portal
email: support@aaf.edu.au
description: Documentation for technical connection to the AAF
baseurl:
permalink: none

markdown: kramdown

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

repository: ausaccessfed/dev-portal

liquid:
  error_mode: strict

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: tutorial

# Ordered by how they should appear in the curriculum list
tutorial_categories:
  - AAF Connection Types
  - Getting Started
  - Integration
  - Federation Manager Authentication
  - Connect a Service
  - Identity Management Solutions
  - Learning Platforms

# New tutorials should be added by running:
#   $ rake tutorial "My tutorial title"
collections:
  connect-with-keycloak:
    output: true
    permalink: /:collection/:name
    title: Connect with Keycloak
    summary: A tutorial for connecting with Keycloak
    category: Identity Management Solutions
    curriculum: OpenID Connect
    level: Intermediate
    tags:
      - keycloak
      - openid connect
      - tutorial
    difficulty: 3
    duration: 20
    published: 2024-02-06
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  connection-types:
    output: true
    permalink: /:collection/:name
    title: Connection Types
    summary: An overview of connection types available
    category: AAF Connection Types
    level: Beginner
    tags:
      - connect
      - overview
    difficulty: 1
    duration: 5
    published: 2024-02-06
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  log-into-federation-manager:
    output: true
    permalink: /:collection/:name
    title: Log into Federation Manager
    summary: A tutorial for logging into Federation Manager
    category: Federation Manager Authentication
    level: Beginner
    tags:
      - authentication
      - federation manager
      - tutorial
    difficulty: 1
    duration: 4
    published: 2024-02-06
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  openid-connect-integration:
    output: true
    permalink: /:collection/:name
    title: OpenID Connect Integration
    summary: A tutorial for OpenID Connect integration
    category: Integration
    curriculum: OpenID Connect
    level: Intermediate
    tags:
      - openid connect
      - tutorial
    difficulty: 3
    duration: 15
    published: 2024-02-06
    author: Kelley Foster <kelley.foster@aaf.edu.au>
  
  rapid-connect-integration:
    output: true
    permalink: /:collection/:name
    title: Rapid Connect Integration
    summary: A tutorial for Rapid Connect integration
    category: Integration
    curriculum: Rapid Connect
    level: Intermediate
    tags:
      - rapid connect
      - tutorial
    difficulty: 3
    duration: 30
    published: 2024-02-06
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  saml-integration:
    output: true
    permalink: /:collection/:name
    title: SAML Integration
    summary: A tutorial for SAML integration
    category: Integration
    curriculum: SAML
    level: Advanced
    tags:
      - saml
      - tutorial
    difficulty: 5
    duration: 60
    published: 2024-02-06
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  connect-an-oidc-service:
    output: true
    permalink: /:collection/:name
    title: Connect an OIDC Service
    summary: A tutorial for connecting an OIDC Service
    category: Connect a Service
    curriculum: OpenID Connect
    level: Intermediate
    tags:
      - openid connect
      - tutorial
    difficulty: 3
    duration: 5
    published: 2024-02-06
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  connect-a-rapid-connect-service:
    output: true
    permalink: /:collection/:name
    title: Connect a Rapid Connect Service
    summary: A tutorial for connecting a Rapid Connect service
    category: Connect a Service
    curriculum: Rapid Connect
    level: Intermediate
    tags:
      - rapid connect
      - tutorial
    difficulty: 3
    duration: 15
    published: 2024-02-06
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  connect-a-saml-service:
    output: true
    permalink: /:collection/:name
    title: Connect a SAML Service
    summary: A tutorial for connecting a SAML service
    category: Connect a Service
    curriculum: SAML
    level: Intermediate
    tags:
      - saml
      - tutorial
    difficulty: 3
    duration: 10
    published: 2024-02-06
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  verifid-integration:
    output: true
    permalink: /:collection/:name
    title: VerifID Integration
    summary: A tutorial for VerifID integration
    category: Integration
    curriculum: VerifID
    level: Intermediate
    tags:
      - tutorial
      - verifid
    difficulty: 3
    duration: 30
    published: 2024-02-14
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  connect-with-verifid:
    output: true
    permalink: /:collection/:name
    title: Connect with VerifID
    summary: A tutorial for connecting with VerifID
    category: Connect a Service
    curriculum: VerifID
    level: Intermediate
    tags:
      - tutorial
      - verifid
    difficulty: 3
    duration: 15
    published: 2024-02-16
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  openid-connect-series:
    output: true
    permalink: /:collection/:name
    title: OpenID Connect Series
    summary: Integrate and connect with OIDC
    curriculum: OpenID Connect
    level: Series
    tags:
      - series
      - intermediate
    difficulty: 3
    duration: 50
    published: 2024-02-28
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  rapid-connect-series:
    output: true
    permalink: /:collection/:name
    title: Rapid Connect Series
    summary: Integrate and connect with Rapid Connect
    curriculum: Rapid Connect
    level: Series
    tags:
      - series
      - intermediate
    difficulty: 3
    duration: 55
    published: 2024-02-29
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  verifid-series:
    output: true
    permalink: /:collection/:name
    title: VerifID Series
    summary: Integrate and connect with VerifID
    curriculum: VerifID
    level: Series
    tags:
      - series
      - intermediate
    difficulty: 3
    duration: 55
    published: 2024-02-29
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  saml-series:
    output: true
    permalink: /:collection/:name
    title: SAML Series
    summary: Integrate and connect with SAML
    curriculum: SAML
    level: Series
    tags:
      - series
      - advanced
    difficulty: 4
    duration: 80
    published: 2024-02-29
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  connect-to-edugain:
    output: true
    permalink: /:collection/:name
    title: Connect to eduGAIN
    summary: A tutorial for connecting to eduGAIN
    category: Connect a Service
    curriculum: eduGAIN
    level: Beginner
    tags:
      - tutorial
      - eduGAIN
    difficulty: 1
    duration: 5
    published: 2024-03-05
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  edugain-integration:
    output: true
    permalink: /:collection/:name
    title: eduGAIN Integration
    summary: A tutorial for eduGAIN integration
    category: Integration
    curriculum: eduGAIN
    level: Advanced
    tags:
      - tutorial
      - eduGAIN
    difficulty: 4
    duration: 30
    published: 2024-03-06
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  edugain-series:
    output: true
    permalink: /:collection/:name
    title: eduGAIN Series
    summary: Integrate and connect with eduGAIN
    curriculum: eduGAIN
    level: Series
    tags:
      - series
      - advanced
    difficulty: 4
    duration: 47
    published: 2024-03-08
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  introduction-to-edugain:
    output: true
    permalink: /:collection/:name
    title: Introduction to eduGAIN
    summary: An overview of eduGAIN
    category: Getting Started
    curriculum: eduGAIN
    level: Intermediate
    tags:
      - tutorial
      - eduGAIN
    difficulty: 3
    duration: 10
    published: 2024-03-08
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  how-to-write-a-tutorial:
    output: true
    permalink: /:collection/:name
    title: Adding & Editing Tutorials - A Guide for Contributors
    summary: How to request changes to content or write your own tutorial
    category: Getting Started
    level: Beginner
    tags:
      - tutorial
    difficulty: 1
    duration: 10
    published: 2024-05-23
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  set-up-sp-in-multiple-federations:
    output: true
    permalink: /:collection/:name
    title: Set up Service Provider in Multiple Federations
    summary: A tutorial for setting up a Service Provider in multiple federations
    category: Integration
    level: Advanced
    tags:
      - tutorial
    difficulty: 5
    duration: 10
    published: 2024-06-14
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  find-your-registered-services:
    output: true
    permalink: /:collection/:name
    title: Find Your Registered Services
    summary: A tutorial for finding your registered services
    category: Connect a Service
    level: Beginner
    tags:
      - tutorial
    difficulty: 1
    duration: 5
    published: 2024-06-21
    author: Kelley Foster <kelley.foster@aaf.edu.au>

  set-up-moodle-via-aaf-authentication:
    output: true
    permalink: /:collection/:name
    title: Connect with Moodle via AAF Authentication
    summary: A tutorial for Setting up Moodle via AAF Authentication
    category: Learning Platforms
    level: Intermediate
    tags:
      - tutorial
    difficulty: 3
    duration: 30
    published: 2025-02-27
    author: Kelley Foster <kelley.foster@aaf.edu.au>

