name: pa11y tests

on: [push]

jobs:
  build:
    name: Building site and running pa11y-ci tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source.
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install jekyll site dependencies.
        uses: ruby/setup-ruby@4c56a21280b36d862b5fc31348f463d60bdc55d5 # v1.301.0
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          working-directory: docs

      - name: Install pa11y-ci dependencies.
        run: yarn install

      - name: Install Ruby gems.
        run: cd docs && bundle install

      - name: markdown lint
        uses: DavidAnson/markdownlint-cli2-action@ce4853d43830c74c1753b39f3cf40f71c2031eb9 # v23.0.0
        with:
          globs: |
            docs/**/*.md
            !docs/assets/**
            !docs/_sass/**

      - name: Start up jekyll server.
        run: yarn start-detached

      - name: Run pa11y-ci.
        run: yarn pa11y-ci:sitemap 2>&1 | tee pa11y_output.txt

      - name: Read pa11y_output file.
        id: pa11y_output
        uses: juliangruber/read-file-action@271ff311a4947af354c6abcd696a306553b9ec18 # v1.1.8
        with:
          path: ./pa11y_output.txt

      - uses: jwalton/gh-find-current-pr@89ee5799558265a1e0e31fab792ebb4ee91c016b # v1.3.3
        id: finder
        with:
          state: all

      - name: Check for pa11y failures.
        if: contains(steps.pa11y_output.outputs.content, 'errno 2')
        run: |
          echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
          exit 1
